# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

# The official Docker image is the current tested and released version of the upstream Vespa container image
FROM docker.io/vespaengine/vespa-minimal:8

