name: Mend CLI Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  mend:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - 'docker.io/vespaengine/vespa:8'
          - 'docker.io/vespaengine/vespa-build-almalinux-8:latest'
          - 'docker.io/vespaengine/vespa-dev-almalinux-8:latest'
          - 'docker.io/vespaengine/vespa-build-almalinux-9:latest'
          - 'docker.io/vespaengine/vespa-dev-almalinux-9:latest'

    steps:
    - name: Downloading Mend CLI
      run: |
        echo Downloading Mend CLI
        curl https://downloads.mend.io/cli/linux_amd64/mend -o /usr/local/bin/mend && chmod +x /usr/local/bin/mend

    - name: Mend CLI Scan
      env:
        MEND_EMAIL: ${{secrets.MEND_EMAIL}}
        MEND_USER_KEY: ${{secrets.MEND_USER_KEY}}
        MEND_URL: https://saas-eu.mend.io
      run: |
        mend image "${{ matrix.image }}"
